### ISSUE TITLE
Roadmap to 1.0

### ISSUE THREAD

**Issue by paultibbetts** [ptibbetts/paultibbetts.uk#1]
- [ ] Add some content - see #2
- [x] Add README #3
- [x] Separate repository for theme #4 
- [x] Develop [theme](https://github.com/ptibbetts/allusion) to 1.0 - see [roadmap](https://github.com/ptibbetts/allusion/issues/1)
- [x] Set up a styleguide #5
- [x] Develop [styleguide](https://github.com/ptibbetts/styles.paultibbetts.uk/) to 1.0 - see [roadmap](https://github.com/ptibbetts/styles.paultibbetts.uk/issues/2)
- [x] Sync content with GitHub #6
